### ISSUE TITLE
Remove Net::Interface

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-engine#149]
Given the age of this module, and the fact that it does not even compile for Linux kernels 3.x, it should be removed and replaced by something else. We cannot release the engine with this module.

Bugs: https://rt.cpan.org/Dist/Display.html?Name=Net-Interface

**Comment by vlevigneron** [comment]
Well... the module that I used to use before in order to provide the same
service (IO::Socket::IP) had issues on Ubuntu. I will spend time to find a
module or a better way to check IPv6 capabilities of a server that could be
compatible with all OS but as it is only usefull for the non regression
tests and does not change engine begaviour, I propose to remove that part
of code and the  corresponding tests for the moment. The coverage will be
worst but I will not prevent from doing the release.

There will be a pull request tomorrow.

2015-11-15 20:43 GMT+01:00 Patrik Wallström <notifications@github.com>:

**Comment by pawal** [comment]
What is the purpose for using either Net::Interface or IO::Socket::IP, is it just to test the code? Why do you need an interface for that? Just so that I understand. Since you do not use real queries going for the network during code coverage tests.

**Comment by vlevigneron** [comment]
Yes, we do not do the same non regression tests on hosts with or without
IPv6 working interfaces.

The engine doesn't do real queries during 'make test', but if there is no
IPv6 on the host, it can not instanciate fake IPv6 servers objects.

As I told you, this is "just" for non regression tests and have a better
coverage. It should not prevent from doing the release, that's why I
propose to remove those tests in the t/* files for the moment.


2015-11-15 23:20 GMT+01:00 Patrik Wallström <notifications@github.com>:

**Comment by vlevigneron** [comment]
The purpose of either Net::Interface or IO::Socket::IP, is it just to test the code, that's correct. That's why it should not prevent from doing a release of the engine.

We do not do real queries during the majority of the tests (we use resluts in .data files instead) except when we test ipv4/ipv6 switch (in this case we don't care about results of the queries, we just check if ipv4/ipv6 is available or not).

I am working on a way to test that without using theses modules, no network, and have the same non regression tests coverage.

First step. I remove all this stuff in order to allow the release of the engine.
Second step, I'll add in the future a new way to tests that part of the engine.

**Comment by sandoche2k** [comment]
@vlevigneron Can this be closed ?

**Comment by sandoche2k** [comment]
Hi Patrik,

   Can you make a release now, so that we could test using CPAN.

Sandoche.

**Comment by pawal** [comment]
@sandoche2k see issue #152.
