### ISSUE TITLE
False positive on open recursive name server

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-engine#171]
Some examples:
- a.nic.ac is not an open resolver, but is reported as such when testing ac.
- ns02.dns.ao is not an open resolver, but is reported as such when testing ao.
- a.nic.sh is not an open resolver, but is reported a such when testing sh.

**Comment by vlevigneron** [comment]
Well, we should modify the algorithm described in specs...
The code is a little different from the specs, it adds a step to check an existing TLD, in case result for a non exiisting domain name query does not answer with a NXDOMAIN. With ns02.dns.ao behaviour we should ask for a domain name like afnic.fr instead of a TLD to detect it does not answer the query.
But do we consider that servers with ns02.dns.ao behaviour need additional testing to give user information about his server uncommon configuration ?
I will modify the code to remove this false positive case, but perhaps we should refine the outputs afterwards...

**Comment by pawal** [comment]
More examples:

ns-d1.tm while testing for tm  
phobos.fccn.pt while testing for cv  
ns-d1.io while testing for io  
ns.utechjamaica.edu.jm while testing for jm

**Comment by sandoche2k** [comment]
@matsduf edited .. (Got to update the below specifications)

Retrieve all address records for all the name servers using Method 4 and Method 5
A SOA query for an certainly nonexistent TLD name sent to the each name server IP address found in step 1, with the flag Recursion Desired (RD) set.
If any answer of the queries made in step 2 contains an RCODE with NXDOMAIN and the AA bit is not set, this test case fails, else continue
If all returns a referal to root with AA bit unset or with a REFUSED, then this test case pass
A SOA query for almost certainly nonexistent names under some TLD is sent to each name server IP address found in step 1 with the RD flag set.
If any answer of the queries made in step 2 contains an RCODE with NXDOMAIN and the AA bit is not set, this test case fails, else continue
7. If all returns a referal to root with AA bit unset or with a REFUSED, then this test case pass
8. If step 4 has been tested five times, stop this test case with WARN
9. Select a new TLD and go to step 5

**Comment by vlevigneron** [comment]
Hi, I guess we missed something. I am working on the implementation of the new algorithm, and (it's not yet finished) I have SERVFAIL on servers that we do not take into account (this servers answer auttoritatives queries). For instance, with zonemaster.net, the server ns2.nic.fr will be considered recursor whereas it is not... Of course it would be better to have a REFUSED instead of a SERVFAIL, but anyway, the server is not a recursor.

Should we modify step 4 and 7 like this:

"If all return a referral to root with no AA bit set, or with a REFUSED or a SERVFAIL, then this test case passes" ???

**Comment by pawal** [comment]
SERVFAIL is a bit of a strange result to receive, but it should not be considered a valid recursive answer. So yes, I think the modification you suggest is something we should do.

**Comment by sandoche2k** [comment]
@vlevigneron Can you have a look at this issue also?

**Comment by sandoche2k** [comment]
@pawal - Seems to have been fixed. Test with the updated version :+1: 

```|
zonemaster-cli tm
Seconds Level     Message
======= ========= =======
  21.98 NOTICE    Nameserver ns-l1.tm has an IP address (80.249.100.44) with mismatched PTR result (ns-d1.tm.).
  55.67 NOTICE    Nameserver ns-d1.tm/64.251.31.180 dropped AAAA query.
  55.70 NOTICE    Nameserver ns-l1.tm/80.249.100.44 dropped AAAA query.
  59.46 NOTICE    SOA 'mname' nameserver (ns1.communitydns.net) is not listed in "parent" NS records for tested zone (ns-a1.tm;ns-a2.tm;ns-a3.tm;ns-a4.tm;ns-d1.tm;ns-l1.tm;ns-y1.tm).
  59.46 NOTICE    SOA 'refresh' value (3600) is less than the recommended one (14400).
  59.47 NOTICE    SOA 'retry' value (1800) is less than the recommended one (3600)
```
and with the old version : https://zonemaster.net/test/e8ee9576df0b8147

**Comment by pawal** [comment]
Here are four TLDs where Zonemaster with this fix cannot determine if the nameserver is an open recursor or not:
http://tldmonitor.blipp.com/tag/RECURSIVITY_UNDEF

**Comment by vlevigneron** [comment]
I did some tests on .mil (which is in your list), for all queries specified in the new spec (the one in this thread we discussed during a F2F meeting, not the one in /doc which has not been updated), the servers reply  NXDOMAIN with AA bit set in all cases. According to the algorithm described above, we reach all the time step 8 (If step 5 has been tested five times, stop this test case with WARN). I guess we miss something if we don't add queries on existing domain names...

**Comment by matsduf** [comment]
My conclusion is that is not wrong to get "WARNING   Can not determine nameservers recursivity." The behavior of the MIL server is wrong:
```
$ dig @199.252.157.234 se soa +norec +mult

; <<>> DiG 9.9.5-3ubuntu0.8-Ubuntu <<>> @199.252.157.234 se soa +norec +mult
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 35024
;; flags: qr aa; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;se.			IN SOA

;; AUTHORITY SECTION:
.			0 IN SOA A.ROOT-SERVERS.NET. NSTLD.VERISIGN-GRS.COM. (
				2016063001 ; serial
				1800       ; refresh (30 minutes)
				900        ; retry (15 minutes)
				604800     ; expire (1 week)
				86400      ; minimum (1 day)
				)

;; Query time: 617 msec
;; SERVER: 199.252.157.234#53(199.252.157.234)
;; WHEN: Fri Jul 01 18:53:13 CEST 2016
;; MSG SIZE  rcvd: 106

```

The ET server has the same problem as MIL. 

The MP servers returns answers with AA unset, ANSWER==0 and status==NOERROR but no referal. That should also be OK. 

One VU server is like the MP servers.

Let us update algorithm to make sure that MP and VU passes, but I see no algorithm that would let MIL and ET pass.
