### ISSUE TITLE
Test Delegation/delegation03 is unreliable

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-engine#18]
Taken from KNOWN_ISSUES:

> This test checks that the smallest possible valid referral packet for a
> domain fits in a non-EDNS0 512-octet UDP packet. It does this by assembling
> the information that must be included, adding it to a packet and then
> checking the size of the resulting packet. Since ldns 1.6.17 and earlier
> does not do name compression in outgoing packets, this test will quite
> often report that packets are too big when in reality they are not.

**Comment by cdybedahl** [comment]
This and issue #19 are not bugs in Zonemaster, they are bugs in ldns. Is it really useful to have them as issues here? Do you think we should try to do workarounds for them? If I had the time, I would like to investigate folding the parts of ldns we actually use into the Net::LDNS C code instead of relying on an external library.

**Comment by pawal** [comment]
I think it is easier to track issues with the Zonemaster software (and its dependencies) if they are documented here.
