### ISSUE TITLE
Hardcoded fake address in t/nameserver.t

### ISSUE THREAD

**Issue by vlevigneron** [dotse/zonemaster-engine#219]
```
Zonemaster->config->no_network( 0 );
my $fail_ns = Zonemaster::Nameserver->new( { name => 'fail', address => '127.0.0.17' } );
my $fail_p = $fail_ns->_query( 'example.org', 'A', {} );
is( $fail_p, undef, 'No return from broken server' );
my ( $e ) = grep { $_->tag eq 'LOOKUP_ERROR' } @{ Zonemaster->logger->entries };
isa_ok( $e, 'Zonemaster::Logger::Entry' );
```

We take a risk that 127.0.017 is really "used"... Should be changed...

**Comment by matsduf** [comment]
Any address could be in use, but it is very unlikely that any address from 127.0.0.0/8 is not on localhost. Can a "icmp ECHO REQUEST" be used to check for the presence of that address?

**Comment by mattias-p** [comment]
I think it's reasonable to assume the TEST-NET-1, TEST-NET-2 or TEST-NET-3 ranges aren't being used. Just picking one of those addresses should be enough.

Is there any meaningful difference between the block of tests mentioned above (at `t/nameserver.t` line 125) and this block at line 62? Except of course that the block at line 125 makes one more test.

    my $broken = new_ok( 'Zonemaster::Nameserver' => [ { name => 'ns.not.existing', address => '192.0.2.17' } ] );
    my $p = $broken->query( 'www.iis.se' );
    ok( !$p, 'no response from broken server' );

If purposes of the respective blocks are equivalent, I suggest they be merged into a single block with the IP address from the block at line 62 and the extra test from the block at line 125.

**Comment by sandoche2k** [comment]
@mattias-p We discussed this recently. Will there be a performance issue in case if there are multiple pings to be done.

**Comment by mattias-p** [comment]
Am I missing something here? I thought this was about testing the behaviour of the Nameserver object when there's no DNS server at the destination?

Since the TEST-NET-ranges are reserved for documentation I think it's safe to assume that they don't respond to DNS. If we can agree on that, we don't have to scan anything at all. Just pick an IP, use it and we're done.

If it turns out for some reason we do need to scan, I think it's better to scan for DNS than to scan for ping. Otherwise we might come across an address that blocks ping but responds to DNS.

**Comment by sandoche2k** [comment]
@vlevigneron pick an address from the documentation address range
