### ISSUE TITLE
Undelegated test behaviour is inconsistent

### ISSUE THREAD

**Issue by aabdnn** [dotse/zonemaster-engine#238]
Zonemaster's undelegated test behaviour is inconsistent, and doesn't quite do what it should. Here's how I believe it should work:

1. If the given name server is not in-zone, and no IP addresses are provided for it, then look up the A and AAAA addresses for it recursively in order to query them.

2. If the given name server is not in-zone, but IP addresses are provided for it, then do NOT query for any other addresses. Query only the given addresses. This is one of the uses of the undelegated test, when an operator is renumbering a name server.

3. If the given name server is in-zone, then NEVER look up any addresses. In-zone name servers should always be given with glue (like in the real world), and zonemaster should abort the test immediately with an error message.

Note that whichever way zonemaster is instantiated (through the CLI or some other application), it should behave the same way, and fail in the same way if the above conditions are not met.

**Comment by sandoche2k** [comment]
@matsduf will create a issue in Zonemaster

**Comment by sandoche2k** [comment]
@aabdnn @matsduf 

If i understand clearly, there are two issues that need to be solved here:

1. Currently, for in-zone resolution, a look-up is done. For an in-zone resolution, the glue should be provided. If not provided, the engine should not stop testing with an error message
2. Any resolution (in-zone or not in-zone), should be done by the "engine" and not by the backend or the CLI

**Comment by matsduf** [comment]
Yes, if glue is **not** provided the Engine should **continue** testing as much as it can without the address, but it should also emit an error that glue is missing. This should be equivalent to testing a delegated domain where glue is missing.

Any resolution of names **not-in-zone** should be done by the Engine so that any failure can be included in the report.

Names **in-zone** should not be resolved to provide address for the delegation, but it could be resolved in the zone itself if possible, but that is a different look-up (authoritative, not glue).

**Comment by matsduf** [comment]
Resolved by PR #285
