### ISSUE TITLE
Default policy level for lack of DNSKEY is ERROR, making unsigned zones be reported as broken

### ISSUE THREAD

**Issue by sandoche2k** [dotse/zonemaster-engine#42]
http://www.zonemaster.net/test/4603

http://dnsviz.net/d/lechatetmoionestcontent.com/VO7EUg/dnssec/

http://dnscheck.iis.se/?time=1424934317&id=4575701&view=basic&test=standard

**Comment by cdybedahl** [comment]
If you think that the result from Zonemaster is somehow incorrect, please specify how.

**Comment by sandoche2k** [comment]
There is an impression in the result from Zonemaster-GUI that there is an error in the DNSSEC configuration for the zone, even when the zone is not signed.

Or maybe should i add this as an issue for the GUI?

**Comment by cdybedahl** [comment]
So the actual problem is that the default log levels for the messages DNSSEC:NO_KEYS_OR_NO_SIGS, DNSSEC:NO_KEYS_OR_NO_SIGS_OR_NO_SOA and DNSSEC:DELEGATION_NOT_SIGNED are set to ERROR. The appropriateness of that is definitely debatable.

Perhaps we should have a special issue tag for "default policy".

**Comment by bortzmeyer** [comment]
Also, for this specific case, there *was* a DS for lechatetmoionestcontent.com (it was recently deleted) so a better example would be dassault.com which was never signed: http://zonemaster.net/test/4614

 192.5.6.30 returned no DS records for dassault.com.
Cannot test DNSKEY signatures, because we got 0 DNSKEY records and 0 RRSIG records.
Cannot test SOA signatures, because we got 0 DNSKEY records, 0 RRSIG records and 1 SOA records.
Delegation from parent to child is not properly signed (no_ds).

**Comment by pawal** [comment]
Is this only a policy issue? Who will fix it?

**Comment by cdybedahl** [comment]
Yes, it is only a policy issue. I don't know who is supposed to decide on the default shipped policy, but I don't think it should be me (which is why I haven't done anything with this).

**Comment by bortzmeyer** [comment]
OK, it is closed but with which decision? :-)

**Comment by pawal** [comment]
Sorry, I updated the policy. See this commit:
https://github.com/dotse/zonemaster-engine/commit/5f6e04805deecf76be97af33681ad2d6eb2d2553

I should have referenced this issue in the commit, but forgot.

**Comment by bortzmeyer** [comment]
@pawal With Github, there is a very convenient feature: put in a commit message "Closes #N" and it will close the issue N and refer to the closing commit.
