### ISSUE TITLE
Problem finding parent?

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-engine#44]
$ zonemaster-cli melbourneit.com.au
    Seconds Level     Message
    ======= ========= =======
       0.90 CRITICAL  Nameservers for "au" provided no NS records for tested zone. RCODE given was NOERROR.
       0.90 CRITICAL  Not enough data about melbourneit.com.au was found to be able to run tests.

No problem doing this test with DNSCheck.

**Comment by cdybedahl** [comment]
Yup, it finds the wrong parent. Looking into why.

**Comment by cdybedahl** [comment]
This turns out to be a bit more interesting than I first thought.

The algorithm we use to find the parent of the domain being tested is to record the steps taken while recursing down to the domain from the root, and then consider the last step that is not the domain itself as the parent. Strictly speaking, this algorithm is broken. If the parent and the grand-parent domain are served from the same servers, it will find the grand-parent rather than the parent. This happens because once we get to the grand-parent servers, they will not refer back to themselves, but instead refer directly to the domain servers, so the actual parent step gets bypassed. Normally, this is no problem for us, since all we want with the parent is to fetch glue and DS records from it, and in this case that works just as well with the grand-parent.

The problem with `melbourneit.com.au` is that `com.au` is served by a _subset_ of the servers that serve `au`. So on the way down in the recursion, we hit one of the `au` servers that do serve `com.au`, which means it knows about `melbourneit.com.au` and sends us directly there, and we think `au` is the parent. Later, when we try to query the parent, we happen to hit one of the `au` servers that do _not_ serve `com.au`, so it gives us a referral instead of glue. Oops.

Patrik, if you try running DNSCheck on `melbourneit.com.au` repeatedly, I suspect strongly that you'll find that it works about 75% of the time (50% chance it hits a `com.au` server on the way down, 50% that it does not when querying parent later, so 0.5*0.5=0.25 probability of failure).

Still thinking about how to best fix this.

**Comment by cdybedahl** [comment]
I have just committed (but not yet pushed or merged) a fix for this. It's not perfect, in that it can still fail for the case where for a domain `a.b.c`, a subset of the servers for `c` are authoritative for `a.b.c` but the intermediate domain `b.c` is served by entirely separate servers (or just a different subset of the servers for `c`). I think that setup is sufficiently exotic that we can ignore it for now, since a perfectly accurate fix would increase the number of queries needed quite significantly and make the code a lot more complex.
