### ISSUE TITLE
Input parameters in log

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-engine#48]
In the SYSTEM module, it would be very useful to have all input parameters listed on the test performed. Such as the name of the domain, and any pre-delegation parameters such as name servers and DS records. The current datetime when the test was started is also useful (for example when debugging RRSIG failures).

In order to do data analysis on the output on many runs, you have to dig down to the BASIC tests to find the args to those, which is not very optimal.

(This is a request from Registry Services.)

**Comment by cdybedahl** [comment]
Fake NS and DS are already logged, but it's necessary to use a logger callback to get at them. It's a bit tricky to add them to the default-returned set of log entries, since adding fake delegation information is not a part of the test execution process. The messages are SYSTEM:ADDED_FAKE_DELEGATION and SYSTEM:FAKE_DS, and their default log level is DEBUG2, so to see them it's probably necessary to use a policy with those levels raised to INFO or NOTICE.

**Comment by pawal** [comment]
Thanks for the info. Would it be possible to log datetime and name of input domain?

**Comment by cdybedahl** [comment]
Will be committed in a moment.

**Comment by cdybedahl** [comment]
I'm putting them on default log level DEBUG, by the way.

**Comment by cdybedahl** [comment]
Closed with commit 8f041d27c566aa2323bf15790297582b5ccbd616.
