### ISSUE TITLE
Handle name servers that timeouts

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-engine#96]
When a name server does not reply, stop sending queries to that name server and return a timeout to the caller. Also log a "blacklist" message saying that the name server has been "blacklisted".

A name server in this case is the combination of address name, IP address and UDP/TCP.

This will limit the number of timeouts that happens and make Zonemaster run faster. Also the number of log entries saying "timeout" will decrease.

**Comment by sandoche2k** [comment]
@vlevigneron  close?

**Comment by vlevigneron** [comment]
I guess we can.

2015-09-09 15:08 GMT+02:00 sandoche2k <notifications@github.com>:

**Comment by cdybedahl** [comment]
The reason we did not implement this from the beginning was the existence of servers that time out when asked for some RR types but not others (an example was `cert.ru`, which timed out on DNSSEC RR types when the DO flag was not set, but they've changed since). Blacklisting only based on name/ip/protocol will make our tests give erroneous results on such servers.
